# Change these first
owner: soapbox-pub # Your GitHub organization or username, where this repository lives
repo: mostr-uptime # The name of this repository

sites:
  - name: Mostr Bridge
    url: https://mostr.pub/api/healthcheck
  - name: Mostr Relay
    url: https://relay.mostr.pub/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.mostr.pub
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Mostr
  introTitle: "Mostr bridge uptime"
  introMessage: "Bridge between ActivityPub and Nostr."
  navbar:
    - title: Status
      href: /
    - title: Code
      href: https://gitlab.com/soapbox-pub/mostr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
